#!/usr/bin/env python3

import argparse

import sys

from test_framework.shell import LocalShell
from test_framework.git import Git

from test_framework.logging import log, init_logging

APTOS_CORE_REPO = "https://github.com/aptos-labs/aptos-core.git"
DOCKER_RUST_BUILD_WORKFLOW_NAME = "workflow-run-docker-rust-build.yaml"


def main() -> None:
    init_logging(logger=log)
    shell = LocalShell()
    git = Git(shell)

    parser = argparse.ArgumentParser(description="Run tests")
    parser.add_argument(
        "--features",
        nargs="*",
        default=[],
        help="Cargo features to enable",
    )
    parser.add_argument(
        "--profile",
        default="release",
        help="Cargo profile to build",
    )
    parser.add_argument(
        "--build-addl-testing-images",
        action="store_true",
        help="Build additional testing images",
    )
    args = parser.parse_args()

    current_git_branch = git.branch()

    # ensure that the current git workspace is clean
    if not git.is_clean():
        log.info("ERROR: Not synced with remote. Please push to a remote branch")
        uncommitted_files = git.run(["status", "--porcelain"]).unwrap().decode().strip()
        log.info("Uncommitted files:\n%s", uncommitted_files)
        sys.exit(1)

    if not git.remote_matches(APTOS_CORE_REPO, current_git_branch):
        log.info("ERROR: Not synced with remote. Please push to a remote branch")
        log.info(
            "%s (local) != %s (remote)",
            git.get_commit_hash(current_git_branch),
            git.get_remote_commit_hash(APTOS_CORE_REPO, current_git_branch),
        )
        sys.exit(1)

    git_sha = git.get_commit_hash("HEAD")
    features = ",".join(args.features)
    profile = args.profile
    build_addl_testing_images = (  # make it a lower case string
        str(args.build_addl_testing_images).lower()
        if type(args.build_addl_testing_images) is bool
        else args.build_addl_testing_images
    )

    log.info("GIT_SHA: %s", git_sha)
    log.info("FEATURES: %s", features)
    log.info("PROFILE: %s", profile)
    log.info("BUILD_ADDL_TESTING_IMAGES: %s", build_addl_testing_images)

    ret = shell.run(
        [
            "gh",
            "workflow",
            "run",
            DOCKER_RUST_BUILD_WORKFLOW_NAME,
            "--ref",
            current_git_branch,
            "--field",
            f"GIT_SHA={git_sha}",
            "--field",
            f"FEATURES={features}",
            "--field",
            f"PROFILE={profile}",
            "--field",
            f"BUILD_ADDL_TESTING_IMAGES={build_addl_testing_images}",
        ],
    )
    log.info("=====")
    log.info(ret.unwrap().decode().strip())
    log.info("=====")
    if ret.succeeded():
        log.info("Successfully triggered workflow")
    else:
        log.info("Failed to trigger workflow")
        sys.exit(1)


if __name__ == "__main__":
    main()
